[package]
name = "dict-gen"
version = "0.1.0"
authors = ["hwuhsi <juny24602@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"